Ansible 4
Otus-DevOps-2018-09/nsemedy_infra pull request #10
Opened 2019-02-13 22:05 UTC by nsemedy

# Выполнено ДЗ №11

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Развернуто локальное окружение
 - Роль db протестирована с помощью Molecule
 - В плейбуках packer_app.yml и packer_db.yml использованы роли app и db

## Как запустить проект:
 - Запустить команду vagrant up в директории ansible

## Как проверить работоспособность:
 - Запустить команду vagrant up в директории ansible

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-02-17 19:11 UTC, mrgreyves requested changes
Здравствуйте!) Проверил ваше дз, замечание оставил к файлу. Пока возвращаю на доработку.

2019-02-17 19:11 UTC, mrgreyves commented on ansible/environments/prod/group_vars/app
> +        - location / {proxy_pass http://127.0.0.1:9292;}
Ошибка =( прокси-пасс не должен быть в одну строку =(

2019-02-17 19:24 UTC, nsemedy commented on ansible/environments/prod/group_vars/app
> +        - location / {proxy_pass http://127.0.0.1:9292;}
исправила

2019-02-18 05:15 UTC, mrgreyves approved these changes
Принимаю!=)

2019-02-18 07:20 UTC, merged